// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDThRK3oXmole51_eEpXYmSpTQLSIF9fPY',
    appId: '1:82845309056:web:cdaef1edc20544762e6e65',
    messagingSenderId: '82845309056',
    projectId: 'myhobi-a1ef3',
    authDomain: 'myhobi-a1ef3.firebaseapp.com',
    storageBucket: 'myhobi-a1ef3.firebasestorage.app',
    measurementId: 'G-9PK81MSJC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2UhnOHSkmZv3JPLg0FZyIGVVVM6tMdp4',
    appId: '1:82845309056:android:b0960c80dcfddca42e6e65',
    messagingSenderId: '82845309056',
    projectId: 'myhobi-a1ef3',
    storageBucket: 'myhobi-a1ef3.firebasestorage.app',
  );

}